import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
main1=pd.read_csv('test.csv')
main1['LotFrontage']=main1['LotFrontage'].fillna(main1['LotFrontage'].mean())
main1['MSZoning']=main1['MSZoning'].fillna(main1['MSZoning'].mode()[0])
main1.drop(['Alley'],axis=1,inplace=True)
main1['BsmtCond']=main1['BsmtCond'].fillna(main1['BsmtCond'].mode()[0])
main1['BsmtQual']=main1['BsmtQual'].fillna(main1['BsmtQual'].mode()[0])
main1['FireplaceQu']=main1['FireplaceQu'].fillna(main1['FireplaceQu'].mode()[0])
main1['GarageType']=main1['GarageType'].fillna(main1['GarageType'].mode()[0])
main1.drop(['GarageYrBlt'],axis=1,inplace=True)
main1['GarageFinish']=main1['GarageFinish'].fillna(main1['GarageFinish'].mode()[0])
main1['GarageQual']=main1['GarageQual'].fillna(main1['GarageQual'].mode()[0])
main1['GarageCond']=main1['GarageCond'].fillna(main1['GarageCond'].mode()[0])
main1.drop(['PoolQC','Fence','MiscFeature'],axis=1,inplace=True)
main1.drop(['Id'],axis=1,inplace=True)
main1['MasVnrType']=main1['MasVnrType'].fillna(main1['MasVnrType'].mode()[0])
main1['MasVnrArea']=main1['MasVnrArea'].fillna(main1['MasVnrArea'].mode()[0])
main1['BsmtExposure']=main1['BsmtExposure'].fillna(main1['BsmtExposure'].mode()[0])
main1['BsmtFinType2']=main1['BsmtFinType2'].fillna(main1['BsmtFinType2'].mode()[0])
main1['Utilities']=main1['Utilities'].fillna(main1['Utilities'].mode()[0])
main1['Exterior1st']=main1['Exterior1st'].fillna(main1['Exterior1st'].mode()[0])
main1['Exterior2nd']=main1['Exterior2nd'].fillna(main1['Exterior2nd'].mode()[0])
main1['BsmtFinType1']=main1['BsmtFinType1'].fillna(main1['BsmtFinType1'].mode()[0])
main1['BsmtFinSF1']=main1['BsmtFinSF1'].fillna(main1['BsmtFinSF1'].mean())
main1['BsmtFinSF2']=main1['BsmtFinSF2'].fillna(main1['BsmtFinSF2'].mean())
main1['BsmtUnfSF']=main1['BsmtUnfSF'].fillna(main1['BsmtUnfSF'].mean())
main1['TotalBsmtSF']=main1['TotalBsmtSF'].fillna(main1['TotalBsmtSF'].mean())
main1['BsmtFullBath']=main1['BsmtFullBath'].fillna(main1['BsmtFullBath'].mode()[0])
main1['BsmtHalfBath']=main1['BsmtHalfBath'].fillna(main1['BsmtHalfBath'].mode()[0])
main1['KitchenQual']=main1['KitchenQual'].fillna(main1['KitchenQual'].mode()[0])
main1['Functional']=main1['Functional'].fillna(main1['Functional'].mode()[0])
main1['GarageCars']=main1['GarageCars'].fillna(main1['GarageCars'].mean())
main1['GarageArea']=main1['GarageArea'].fillna(main1['GarageArea'].mean())
main1['SaleType']=main1['SaleType'].fillna(main1['SaleType'].mode()[0])
print(main1.shape)
main1.to_csv('formulated.csv',index=False)